#mapCountryDataTesting.r
#andy south 6/11/12

#testing an error generated by the vignette following a recent change

## Error in image.default(iy, ix, t(iz), xaxt = "n", yaxt = "n", xlab = "",  :
##                         must have one more break than colour
                       


library(rworldmap)

data("countryExData",envir=environment())

sPDF <- joinCountryData2Map(countryExData,
                            joinCode = "ISO3",
                            nameJoinColumn = "ISO3V10",
                            mapResolution = "coarse"
)
mapParams <- mapCountryData( sPDF,
                             nameColumnToPlot="BIODIVERSITY",
                             addLegend=FALSE,
                             oceanCol="lightblue",
                             missingCountryCol="grey"
)

colourVector = mapParams[["colourVector"]]
cutVector = mapParams[["cutVector"]]

#warning("colourVector=",colourVector)
#warning("mapParams=",mapParams)

#warning(paste("length colourVector=",length(mapParams$colourVector),"length cutVector=",length(cutVector),"\n"))
#warning(paste("length colourVector=",length(colourVector),"length cutVector=",length(cutVector),"\n"))

warning(paste("length colourVector=",length(mapParams$colourVector),"\n"
              ,"length cutVector=",length(mapParams$cutVector),"\n"
              ,"length plottedData=",length(mapParams$plottedData),"\n"
              ,"catMethod=",mapParams$catMethod,"\n"
              ,"colourPalette=",mapParams$colourPalette,"\n"
))

addMapLegend(colourVector = colourVector,
             cutVector = cutVector, 
             legendLabels="all",
             legendWidth=0.5,
             legendMar = 2
)
